export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const SET_LOADING_ORDERS = 'SET_LOADING_ORDERS';
export const DELETE_ORDER_WITH_ID = 'DELETE_ORDER_WITH_ID';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';